org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096M
github.dotcom.specUrl=https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/api.github.com/api.github.com.json
github.ghes.specUrl=https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/ghes-3.22/ghes-3.22.json
github.dotcom.sha=9fa7d76335f0d8b708808deaf56169d4e0ea398e
