org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096M
github.dotcom.specUrl=https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/api.github.com/api.github.com.json
github.ghes.specUrl=https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/ghes-3.22/ghes-3.22.json
github.dotcom.sha=2c235629da4ac385190a0f2726113a7f72fa2ead
