org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096M
github.dotcom.specUrl=https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/api.github.com/api.github.com.json
github.ghes.specUrl=https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/ghes-3.21/ghes-3.21.json
github.dotcom.sha=f3d501cd78ec0feeb42b2bf433d58aa2071a254b
